---
- name: ec2 creator
  hosts: localhost
  connection: local
  vars:
    keypair: webserver
    instance_type: t2.micro
    image: ami-07c1207a9d40bc3bd
    region: us-east-2
    group: ansible
  tasks:
    - name: Create a security group in AWS for SSH access and HTTP
      ec2_group:
         name: "{{ group }}"
         description: Ansible Security Group
         region: "{{ region }}"
         rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0

    - name: Provision an instance
      ec2:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        group: "{{ group }}"
        wait: true
        exact_count: 1
        count_tag:
          Name: AnsibleWebservers
        instance_tags:
          type: development
        vpc_subnet_id: subnet-66b18d1c
        wait: yes
        assign_public_ip: yes
      register: ec2

    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: ansiblehosts
      with_items: "{{ ec2.instances }}"
    
    - name: Show group
      debug:
        var: groups.ansiblehosts
