- name: Terminate instances and Remove Private network
  hosts: localhost
  vars:
    name: ansible
    region: us-east-2
    instance_ids:
        - 'i-0d7b86c0c08fef8f7'
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        region: "{{ region }}"
        state: 'absent'
        instance_ids: '{{ instance_ids }}'
    - name: Remove ansible security group
      ec2_group:
        name: "{{ name }}"
        region: "{{ region }}"
        state: absent