- name: Terminate instances and Remove Private network
  hosts: localhost
  vars:
    name: ansible
    region: us-east-2
    instance_ids:
        - 'i-04036375f48b8841f'
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        region: "{{ region }}"
        state: 'absent'
        instance_ids: '{{ instance_ids }}'
    - name: Remove ansible security group
      ec2_group:
        name: "{{ region }}"
        region: "{{ region }}"
        state: absent